 <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?=root_js;?>jquery.js"></script>
    <script>
        var imgRaty = "<?php echo root.'raty-2.7.0/lib/images' ;?>";
        console.log(imgRaty);
    </script> 
    <script src="<?=root_js;?>jquery.raty.js"></script>
    <script src="<?=root_js;?>commentaire.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?=root_js;?>bootstrap.min.js"></script>

</body>

</html>
