<?php include("globals/header.phtml") ?>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <h1 class="page-header">
                    Ben's Blog
                    <small>Best blog ever #swag</small>
                </h1>
<?php foreach ($article as $key => $value): ?>
                <h2>
                    <a href="#"><?php echo $value["titre"] ?></a>
                </h2>
                <p class="lead">
                    by <a href="index.php"><?php echo $value["auteur"] ?></a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on <?php echo $value["date_article"] ?></p>
                <img class="img-responsive" src="vues/images/<?php echo $value["image"] ?>" alt="">
                <hr>
                <p><?php echo $value["description"] ?></p>
                <a class="btn btn-primary" href="index.php?page=article&id=<?php echo $value['id'] ?>">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
<?php endforeach; ?>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>
            <!-- Blog Sidebar Widgets Column -->
<?php include("globals/sidebar.phtml") ?>
<?php include("globals/footer.phtml") ?>
       