<?php include("globals/header.phtml") ?>

<!-- Page Content -->
<div class="container">

	<div class="row">

		<!-- Blog Post Content Column -->

		<div class="col-lg-8">

			<!-- Blog Post -->

			<!-- Title -->
			<h1><?php echo $readmore["titre"] ?></h1>
			<a href="index.php?page=ajouterfavoris&id=<?php echo $readmore['id'] ?>"> Ajouter aux favoris </a> 

			<!-- Author -->
			<p class="lead">
				by <a href="#"><?php echo $readmore["auteur"] ?></a>
			</p>

			<hr>

			<!-- Date/Time -->
			<p><span class="glyphicon glyphicon-time"></span> Posted on <?php echo $readmore["date_article"] ?></p>

			<hr>

			<!-- Preview Image -->
			<img class="img-responsive" src="vues/images/<?php echo $readmore["image"] ?>" alt="">

			<hr>

			<!-- Post Content -->
			<p class="lead"><?php echo $readmore["description"] ?></p>

			<hr>

			<!-- Blog Comments -->

			<?php if(empty($error) == false): ?>
				<div class="alert alert-danger">
					<ul>
					<?php foreach ($error as $key => $value): ?>
						<li>
							<?php echo $value ?>
						</li>
					<?php endforeach; ?>
					</ul>
				</div>
			<?php endif; ?>



			<?php if(empty($successCommentaire) == false): ?>
				<div class="alert alert-success">
					<p><?php echo "votre commentaire a bien été enregistré !" ?></p>
				</div>
			<?php endif; ?>

			<!-- Comments Form -->
			<div class="well">
				<h4>Leave a Comment:</h4>
				<form method="POST" role="form">
					<div class="form-group">
						<input type="text" name="auteur" placeholder="Auteur">
						<div class="stars"></div>
						<br>
						<textarea class="form-control" rows="3" name="contenu" placeholder="Entrez votre commentaire içi"></textarea>
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>

			<hr>

			<!-- Comment -->
			<?php foreach ($comment as $key => $value): ?>
			<div class="media">
				<a class="pull-left" href="#">
					<img class="media-object" src="http://placehold.it/64x64" alt="">
				</a>

				<div class="media-body">
					<h4 class="media-heading"><?php echo $value["auteur"] ?>
						<small><?php echo $value["date_commentaire"] ?></small>
					</h4>
					<div class="starscom" data-score="<?php echo $value["note"] ?>">
					</div>
					<?php echo htmlentities($value["contenu"]) ?>

				</div>
			</div>
			<?php endforeach; ?>
	</div> <!-- col-8 -->

	

	<?php include("globals/sidebar.phtml") ?>

	</div> <!-- row -->
</div> <!-- container -->

<hr>
<?php include("globals/footer.phtml") ?>