<?php include("globals/header.phtml") ?>


<div class="container">

  <div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
      </p>
      <div class="jumbotron">
        <h1>Categories</h1>
      </div>
      <div class="row">
        <?php foreach ($categories as $key => $value): ?>
        <div class="col-xs-6 col-lg-4">
          <h2><?php echo $value["titre"] ?></h2>
          <p><?php echo $value["description"] ?></p>
          <p><a class="btn btn-default" href="index.php?page=unecategorie&id=<?php echo $value['id'] ?>" role="button">View details &raquo;</a></p>
        </div><!--/.col-xs-6.col-lg-4-->
      <?php endforeach; ?>                

    </div><!--/row-->
  </div><!--/.col-xs-12.col-sm-9-->

  <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
    <?php foreach ($categories as $key => $value): ?>
    <div class="list-group">
      <a href="index.php?page=unecategorie&id=<?php echo $value['id'] ?>" class="list-group-item active"><?php echo $value["titre"] ?></a>
    </div>
     <?php endforeach; ?>   
  </div><!--/.sidebar-offcanvas-->
</div><!--/row-->

<hr>

<?php include("globals/footer.phtml") ?>

