
<?php include("globals/header.phtml"); ?>

<form class="form-signin" method="POST" novalidate>
  <h2 class="form-signin-heading">Please sign in</h2>
  <label class="sr-only">Email address</label>
  <input type="email" name="login" id="login" class="form-control" placeholder="Email address">
  <label class="sr-only">Password</label>
  <input type="password" name="password" id="password" class="form-control" placeholder="Password">
  <div class="checkbox">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>

<?php include("globals/header.phtml"); ?>

<?php include("globals/header.phtml"); ?>