<?php include("globals/header.phtml") ?>
<h1> Mes favoris </h1>
<a href="index.php?page=favoris&supprimer=true>"> Supprimer tous les favoris </a>
<!-- Page Content -->
<div class="container">

	<div class="row">

		<!-- Blog Post Content Column -->

		<div class="col-lg-8">

			<!-- Blog Post -->
			<?php foreach ($articlefavoris as $key => $value): ?>

			<!-- Title -->
			<a href="index.php?page=article&id=<?php echo $value->getId() ?>"><h1><?php echo $value->getTitre() ?></h1></a>

			<!-- Author -->
			<p class="lead">
				by <a href="#"><?php echo $value->getAuteur() ?></a>
			</p>

			<hr>

			<!-- Date/Time -->
			<p><span class="glyphicon glyphicon-time"></span> Posted on <?php echo $value->getDateArticle() ?></p>

			<hr>

			<!-- Preview Image -->
			<img class="img-responsive" src="vues/images/<?php echo $value->getImage() ?>" alt="">

			<hr>

			<!-- Post Content -->
			<p class="lead"><?php echo $value->getDescription() ?></p>

		<?php endforeach; ?>
		</div> <!-- col-8 -->
	</div>
</div>		

<?php include("globals/sidebar.phtml") ?>
<?php include("globals/footer.phtml") ?>
